import type { Metadata } from "next";
import "@/src/styles/globals.scss";
import Layout from "../components/common/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-base-black antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
